name: Maven build CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Download dependencies
      run: |
        mvn --no-transfer-progress install:install-file -Dfile=freenet.jar -DgroupId=org.freenetproject -DartifactId=fred -Dversion=0.7.5.1387 -Dpackaging=jar
        mvn --no-transfer-progress install:install-file -Dfile=freenet-ext.jar -DgroupId=org.freenetproject -DartifactId=freenet-ext -Dversion=29 -Dpackaging=jar
        mvn --no-transfer-progress install:install-file -Dfile=commons-io-2.0.1.jar -DgroupId=org.apache.commons -DartifactId=commons-io -Dversion=2.0.1 -Dpackaging=jar
    - name: Build with Maven
      run: mvn package
    - name: Generate Javadoc
      run: mvn javadoc:javadoc
    - name: Upload N2NChat
      uses: actions/upload-artifact@v4
      with:
        name: N2NChat
        path: .
